LAF ADD_KIT_EX
INT_VAR
  kit_class = 2
  lower     = RESOLVE_STR_REF(@101)
  mixed     = RESOLVE_STR_REF(@102)
  help      = RESOLVE_STR_REF(@104)
STR_VAR
  kit_name  = ~A7_SPELLSWORD~
  unusable  = ~0x00010008~
  clasweap  = ~1 1 1 1 1 1 1 1~
  weapprof  = ~1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  abclasrq  = ~9 0 0 0 9 0~
  abclsmod  = ~0 0 0 0 0 0~
  abdcdsrq  = ~17 0 0 0 17 0~
  abdcscrq  = ~15 0 0 0 15 0~
  alignmnt  = ~1 1 1 1 1 1 1 1 1~
  dualclas  = ~0 1 1 1 1 0~
  clab_path = EVAL ~%MOD_FOLDER%/original/A7cbspsd.2da~
  kittable  = ~K_F_H K_F_D K_F_G K_F_E K_F_HE K_F_HL K_F_HO~
  luabbr    = ~Fi0~
  stweap    = ~LEAT17 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 * * * POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
  bdstweap  = ~LEAT05 * HELM01 * RING06 * * * * * BELT02 * * * POTN08,5 POTN17,3 * HAMM02 SW1H05 STAF02~
RET
  kit_id
END


// level-specific spellsword weapons (blade only)...
COPY ~%MOD_FOLDER%/original/A7blad03.itm~ ~override~
  SAY NAME1 @120
  SAY NAME2 @120

COPY ~%MOD_FOLDER%/original/A7blad06.itm~ ~override~
  SAY NAME1 @121
  SAY NAME2 @121

COPY ~%MOD_FOLDER%/original/A7blad09.itm~ ~override~
     ~%MOD_FOLDER%/original/A7blad12.itm~ ~override~
  SAY NAME1 @122
  SAY NAME2 @122

COPY ~%MOD_FOLDER%/original/A7blad15.itm~ ~override~
  SAY NAME1 @123
  SAY NAME2 @123

COPY ~%MOD_FOLDER%/original/A7blad18.itm~ ~override~
  SAY NAME1 @124
  SAY NAME2 @124

COPY ~%MOD_FOLDER%/original/A7blad24.itm~ ~override~
  SAY NAME1 @125
  SAY NAME2 @125


// Summon Blade Spirit ability
COPY ~%MOD_FOLDER%/original/A7sp103.bam~ ~override~

COPY ~%MOD_FOLDER%/original/A7sp103.spl~ ~override~
  SAY NAME1 @150
  SAY UNIDENTIFIED_DESC @152

COPY ~%MOD_FOLDER%/original/A7blad03.cre~ ~override~
     ~%MOD_FOLDER%/original/A7blad06.cre~ ~override~
     ~%MOD_FOLDER%/original/A7blad09.cre~ ~override~
     ~%MOD_FOLDER%/original/A7blad12.cre~ ~override~
     ~%MOD_FOLDER%/original/A7blad15.cre~ ~override~
     ~%MOD_FOLDER%/original/A7blad18.cre~ ~override~
     ~%MOD_FOLDER%/original/A7blad24.cre~ ~override~
  SAY NAME1 @151
  SAY NAME2 @151
